apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-script-configmap
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  script.sql: |  
    CREATE SCHEMA IF NOT EXISTS claims
    AUTHORIZATION claimdb;

    DROP TABLE IF EXISTS claims.claims CASCADE;
    DROP TABLE IF EXISTS claims.original_images CASCADE;
    DROP TABLE IF EXISTS claims.processed_images CASCADE;
    DROP SEQUENCE IF EXISTS claims.claims_id_seq CASCADE;
    DROP SEQUENCE IF EXISTS claims.original_images_id_seq CASCADE;
    DROP SEQUENCE IF EXISTS claims.processed_images_id_seq CASCADE;

    -- SEQUENCE: claims.claims_id_seq

    CREATE SEQUENCE IF NOT EXISTS claims.claims_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

    -- Table: claims.claims

    CREATE TABLE IF NOT EXISTS claims.claims
    (
        id integer NOT NULL DEFAULT nextval('claims.claims_id_seq'::regclass),
        claim_number text COLLATE pg_catalog."default",
        category text COLLATE pg_catalog."default",
        policy_number text COLLATE pg_catalog."default",
        client_name text COLLATE pg_catalog."default",
        subject text COLLATE pg_catalog."default",
        body text COLLATE pg_catalog."default",
        summary text COLLATE pg_catalog."default",
        location text COLLATE pg_catalog."default",
        "time" text COLLATE pg_catalog."default",
        sentiment text COLLATE pg_catalog."default",
        CONSTRAINT claims_pkey PRIMARY KEY (id)
    )
    WITH (
        OIDS = FALSE
    )
    TABLESPACE pg_default;

    -- Link Table to Sequence    

    ALTER SEQUENCE claims.claims_id_seq 
        OWNED BY claims.claims.id;

    -- SEQUENCE: claims.original_images_id_seq

    CREATE SEQUENCE IF NOT EXISTS claims.original_images_id_seq
        INCREMENT 1
        START 1
        MINVALUE 1
        MAXVALUE 2147483647
        CACHE 1;

    -- Table: claims.original_images

    CREATE TABLE IF NOT EXISTS claims.original_images
    (
        id integer NOT NULL DEFAULT nextval('claims.original_images_id_seq'::regclass),
        image_name text COLLATE pg_catalog."default" NOT NULL,
        image_key text COLLATE pg_catalog."default" NOT NULL,
        claim_id integer NOT NULL,
        CONSTRAINT original_images_pkey PRIMARY KEY (id),
        CONSTRAINT fk_claim_id FOREIGN KEY (claim_id)
            REFERENCES claims.claims (id) MATCH SIMPLE
            ON UPDATE CASCADE
            ON DELETE CASCADE
    )
    WITH (
        OIDS = FALSE
    )
    TABLESPACE pg_default;

    -- Link Table to Sequence    

    ALTER SEQUENCE claims.original_images_id_seq 
        OWNED BY claims.original_images.id;

    -- SEQUENCE: claims.processed_images_id_seq

    CREATE SEQUENCE IF NOT EXISTS claims.processed_images_id_seq
        INCREMENT 1
        START 1
        MINVALUE 1
        MAXVALUE 2147483647
        CACHE 1;

    -- Table: claims.processed_images

    CREATE TABLE IF NOT EXISTS claims.processed_images
    (
        id integer NOT NULL DEFAULT nextval('claims.processed_images_id_seq'::regclass),
        image_name text COLLATE pg_catalog."default" NOT NULL,
        image_key text COLLATE pg_catalog."default" NOT NULL,
        claim_id integer NOT NULL,
        CONSTRAINT processed_images_pkey PRIMARY KEY (id),
        CONSTRAINT fk_claim_id FOREIGN KEY (claim_id)
            REFERENCES claims.claims (id) MATCH SIMPLE
            ON UPDATE CASCADE
            ON DELETE CASCADE
    )
    WITH (
        OIDS = FALSE
    )
    TABLESPACE pg_default;

    -- Link Table to Sequence    

    ALTER SEQUENCE claims.processed_images_id_seq 
        OWNED BY claims.processed_images.id;

    -----
    -- INSERTS
    -----
    -- CLAIM1

    INSERT INTO claims.claims (claim_number, category, policy_number, client_name, subject, body, summary, location, time, sentiment) 
    VALUES ('1', 'Refund', 'PNR-9W5TY76', 'Parth Sharma','Claim for Refund - PNR-9W5TY76', '
    Hi Indigo Airlines,
    
    I hope this email finds you well. My name is Parth Sharma, and I am writing to file a claim for my flight from Mumbai to Delhi on March 31, 2024. My PNR is 9W5TY76.

    at 12.20 PM from Mumbai to Gwalior and at 11.00 am, I am receiving a message that my flight has been cancelled and there are no other flights later in the day!!.\n\n Do you guys understand the importance of bookings? Can’t you keep few hours delay and arrange the flight? Stupid reasons for your inefficiency weather is now under controlled. In case the situation was

    so worse it should have been informed to the passengers last night itself, so that they would made some arrangements or plan accordingly, just informing before 2 hours is highly irresponsible and passengers were already at the airport. The airport staff was rude and haggled the passengers unnecesarily. 

        
    Thank you for your assistance, and I look forward to a swift resolution of this claim.

    Sincerely,

    Parth Sharma
    Gurgaon
    DLF Phase 1,  98765
    (91) 9798909852
    parth.sharma@gmail.com
      
    ',
    '',
    '',
    '',
    ''
    );

    -- CLAIM2

    INSERT INTO claims.claims (claim_number, category, policy_number, client_name, subject, body, summary, location, time, sentiment) 
    VALUES ('2', 'Baggage Damage', 'PNR: 76AT54F2', 'Alisha','Urgent: Unacceptable Damage of Backage with valuables', '
    Hi Indigo,

    I am writing to express my extreme dissatisfaction with the appalling service I have received on my last flight. This is regarding my baggage that got damaged during my flight from Guwahati to Delhi on July 2, 2024. 
    
    The luggage had my clothes and some luxury perfumes which broke. The suitcase is now completely damaged. To make matters worse, the on-ground staff refused to acknowledge the damage and said the suitcase was probably 
    
    broken before. I am sending a mail to the Ministry of Aviation as well regarding this. The entire experience is extremely dissapointing specially for someone who is a frequent flyer with Indigo since your inception days. 
    
    Please look into the same. I will personally make sure that neither me nor my family/friends will fly Indigo if no action is taken into this. 
    
    Sincerely, 
    Alisha  
    Bengaluru 
    8899006633 
    alishasingh@gmail.com

    The accident occurred on January 15, 2024, at approximately 3:45 PM, near the intersection of Maple Street and Oak Avenue in Rivertown. My vehicle, a Silver Hawk GT, was struck by another driver, identified as Samantha Reynolds, who ran a red light at the aforementioned intersection. This incident resulted in substantial damage to the front end of my car, including severe structural damage and airbag deployment.

    I reported the claim immediately after the accident, providing all necessary details, witness information, and a detailed description of the events leading up to the collision. However, the response—or lack thereof—from your company has been absolutely deplorable. I have yet to receive any updates on the status of my claim, and my attempts to contact your claims department have been met with prolonged hold times and unhelpful representatives.

    I insist on a thorough investigation into this matter and demand an explanation for the unreasonable delay. It is my right as a policyholder to receive timely updates on the progress of my claim and to be treated with the respect and urgency that this situation demands.

    Furthermore, the lack of transparency and communication from your company is not only unprofessional but also exacerbates the stress and inconvenience caused by the accident itself. I expect immediate action to be taken to expedite the processing of my claim and provide me with the information I am entitled to as a paying customer.

    I am appalled at the disregard for customer satisfaction and the apparent negligence displayed by your company in handling my claim. If my concerns are not addressed promptly and to my satisfaction, I will have no choice but to escalate this matter to the appropriate regulatory authorities and consider legal action.

    I demand a comprehensive update on the status of my claim within the next 48 hours. Failing to meet this deadline will only reinforce my belief that your company values its bottom line over the well-being of its customers.

    I trust that you will treat this matter with the urgency and seriousness it deserves.

    Sincerely,
    John T. Anderson
    Policy Number: PT-567890
    
    ',
    '',
    '',
    '',
    ''
    );

    -- CLAIM3

    INSERT INTO claims.claims (claim_number, category, policy_number, client_name, subject, body, summary, location, time, sentiment) 
    VALUES ('3', 'Review', 'PNR-98A765PO', 'Mohit Jain','Urgent: Great Service in the Sky', '
    Dear Indigo Airlines,

    I hope this email finds you well.
    
    My name is Mohit Jain and I am wrtiting a small appreciation note for you people. Every time I fly Indigo, you people surprise me with a note and a little present. Almost to the point that if I don’t get one, it would be a surprise😜 
    
    This is not a flex but rather some observations I glean from experiences like this. A packet of chips & cookies cost nothing but it shows customers you care & makes them feel special. Indigo also brings out the letter and the gift on a 
    
    tray making it visible to others and sending a signal that celebs fly with us too. This builds the airlines’ aspirational positioning. While everything these days is snapped for social media, these little initiatives usually end up as a post as well, like this one. 
    
    So thanks once again for the fantastic service.  Looking forward to flying again soon.

    Sincerely,

    Mohit Jain
    
    ',
    '',
    '',
    '',
    ''
    );

    -- CLAIM4

    INSERT INTO claims.claims (claim_number, category, policy_number, client_name, subject, body, summary, location, time, sentiment) 
    VALUES ('4', 'Review', 'PNR-76AT54F2', 'Vikram Singh','Appreciation Message', '
    Dear Indigo,

    My name is Vikram Singh and I am wrtiting a small appreciation note for you people. Every time I fly Indigo, you people surprise me with a note and a little present. Almost to the point that if I don’t get one, it would be a surprise😜 
    
    This is not a flex but rather some observations I glean from experiences like this. A packet of chips & cookies cost nothing but it shows customers you care & makes them feel special. Indigo also brings out the letter and the gift 
    
    on a tray making it visible to others and sending a signal that celebs fly with us too. This builds the airlines’ aspirational positioning. While everything these days is snapped for social media, these little initiatives usually end up 
    
    as a post as well, like this one. 
    
    Sincerely, 
    Vikram Singh  
    Gurugram, Haryana 
    990088331 
    vikramsingh@gmail.com" 
   
    ',
    'The email is from a customer named Dominic Toretto, requesting to file a claim for a car accident that occurred in Los Angeles. He describes the incident as involving a high-speed chase with another driver named Johnny Tran, who cut through traffic and caused Dominic to take evasive action. Dominic attempted to clear the truck by launching his car off a ramp but ended up crashing into a billboard, causing significant damage to the front end, shattered windows, and possibly a twisted chassis. The sender expresses confidence in Parasol''s ability to handle the claim efficiently due to their long-term loyalty as a customer. They ask for guidance on the next steps to take in the claims process.',
    'The event the claim is related to happened at the intersection of Sunset Boulevard and Vine Street in downtown Los Angeles.',
    'The event described in the claim text occurred last night (no specific date mentioned) at an intersection in downtown Los Angeles, specifically at Sunset Boulevard and Vine Street. The exact time is not provided in the text.',
    'The person sending the claim, identified as Dominic Toretto, expresses a positive sentiment towards Parasol Insurance and his expectation of them handling his claim efficiently. However, the tone of the email is also boastful and exaggerated, describing an unlikely series of events involving a car accident and a high-speed chase. Despite the unconventional circumstances, Dominic expresses confidence in Parasol''s ability to help him get his car repaired.'
    );

    -- CLAIM5

    INSERT INTO claims.claims (claim_number, category, policy_number, client_name, subject, body, summary, location, time, sentiment) 
    VALUES ('5', 'Review', 'PNR: 89PL2T1', 'Lavanya Singh', 'Meal not served, rude behaviour', '
    
    Hi Indigo,

    I am absolutely *thrilled* (read: infuriated) to be writing yet another heartfelt missive to the void that is your customer service. I am writing to complaint a claim 
    
    for a recent flight I took from Bengaluru to Nashik. I caught the flight on June 9th, 2024, at  3:30 PM. My PNR number is 89PL2T1.\n\n I wanted to report about an incident that took 
    
    place during the flight. I had pre-ordered and paid for a Chicken Junglee sandwich. However, the cabin staff told that the Chicken Junglee Sandwich was out of stock and fhence provided me an alternate meal. 
    
    The meal provided to me was a box of cashews and some cookies. The cookies received were stale and out of date. When I asked for a replacement, I was told this is all they have and they cannot provide anything else. 
    
    Not even a complimentary drink. The entire experience was not at all pleasant and the rude behaviour of the staff on-board was just not acceptful. It is shameful that a airlines of this pedigree provides such an experience to its flyers. 
    
    Please look into the same. I will personally make sure that neither me nor my family/friends will fly Indigo if no action is taken into this. 
    
    Looking forward to an expedited resolution.
    
    Lavanya Singh 
    Bengaluru 
    9993388221 
    lavanyasingh@gmail.com
    
    ',
    'The text is a letter from a customer named Saul Goodman to the Stoneheart Insurance Claims Department regarding an unresolved car accident claim. The incident occurred on March 28, 2023, at the intersection of 5th Avenue and Main St in Springfield, where Saul''s car was hit by another vehicle that ran a red light. He is frustrated with the lack of progress on his claim, which has been ongoing for over two weeks. Saul demands a thorough review and update within 24 hours, threatening further actions if his request is not met. He attaches relevant documents, including a police report, photos of the incident, and records of calls and emails, to support his claim.',
    'The event the claim is related to happened at the intersection of 5th Avenue and Main St in Springfield.',
    'The car accident described in the text occurred on March 28, 2023, at around 4:15 PM.',
    'The sentiment of the person sending this claim is one of frustration and urgency. They are expressing dissatisfaction with the delay in processing their car accident claim and threatening further action if it is not resolved promptly.'
    );

    -- CLAIM6
    
    INSERT INTO claims.claims (claim_number, category, policy_number, client_name, subject, body, summary, location, time, sentiment) 
    VALUES ('6', 'Refund', 'PNR - 987B65A4Z', 'Amit Pal', 'Last minute flight cancellation', '
    Dear Indigo,

    My name is Amit, and I am writing to complaint for flight booked today on Jun 20, 2024 at 12.20 PM from Mumbai to Gwalior and at 11.00 am, I am receiving a message that my flight has been cancelled 
    
    and there are no other flights later in the day!!.\n\n Do you guys understand the importance of bookings? Can’t you keep few hours delay and arrange the flight? Stupid reasons for your inefficiency weather is not under controll. 
    
    In case the situation was so worse it should have been informed to the passengers last night itself, so that they would made some arrangements or plan accordingly, just informing before 2 hours is highly irresponsible and passengers were 
    
    already at the airport. This is higly irresponsibile on part of the airlines and I shall file a complaint to the Ministry of Aviation as well regarding this. This is not how a Frequent Flyer of your airline desrves to be treated. Please make 

    sure that the matter is duly looked into and the an appropriate action taken. I seek a refund and a COMPLETE one in this case for the experience I faced.
    
    Sincerely, 
    Amit  
    Nagpur, 
    9965926239 
    amitjainh@gmail.com
    
    ',
    '',
    '',
    '',
    ''
    );

    -- IMAGES

    INSERT INTO claims.original_images (image_name, image_key, claim_id) VALUES ('car0.jpg', 'original_images/car0.jpg', 1);
    INSERT INTO claims.original_images (image_name, image_key, claim_id) VALUES ('car1.jpg', 'original_images/car1.jpg', 1);
    INSERT INTO claims.original_images (image_name, image_key, claim_id) VALUES ('car2.jpg', 'original_images/car2.jpg', 2);
    INSERT INTO claims.original_images (image_name, image_key, claim_id) VALUES ('car3.jpg', 'original_images/car3.jpg', 3);
    INSERT INTO claims.original_images (image_name, image_key, claim_id) VALUES ('car5.jpg', 'original_images/car5.jpg', 3);
    INSERT INTO claims.original_images (image_name, image_key, claim_id) VALUES ('car6.jpg', 'original_images/car6.jpg', 3);
    INSERT INTO claims.processed_images (image_name, image_key, claim_id) VALUES ('car0-processed.jpg', 'processed_images/car0-processed.jpg', 1);
    INSERT INTO claims.processed_images (image_name, image_key, claim_id) VALUES ('car1-processed.jpg', 'processed_images/car1-processed.jpg', 1);
    INSERT INTO claims.processed_images (image_name, image_key, claim_id) VALUES ('car2-processed.jpg', 'processed_images/car2-processed.jpg', 2);
    INSERT INTO claims.processed_images (image_name, image_key, claim_id) VALUES ('car3-processed.jpg', 'processed_images/car3-processed.jpg', 3);
    INSERT INTO claims.processed_images (image_name, image_key, claim_id) VALUES ('car5-processed.jpg', 'processed_images/car5-processed.jpg', 3);
    INSERT INTO claims.processed_images (image_name, image_key, claim_id) VALUES ('car6-processed.jpg', 'processed_images/car6-processed.jpg', 3);


